ADD file:4eedf861fb567fffb2694b65ebdd58d5e371a2c28c3863f363f333cb34e5eb7b in / 
CMD ["/bin/bash"]
/bin/sh -c apt-get update && apt-get install -y  aspcud bzip2 curl g++ git libgdbm-dev libncurses5-dev make m4     pkg-config sudo unzip wget gnupg bioperl python-biopython
/bin/sh -c apt-get update && apt-get install -y cmake g++ zlib1g-dev libboost-dev libboost-program-options-dev --fix-missing
/bin/sh -c wget ftp://pbil.univ-lyon1.fr/pub/logiciel/silix/silix-1.2.9.tar.gz &&   tar xf silix-1.2.9.tar.gz &&   rm silix-1.2.9.tar.gz &&   cd silix-1.2.9 &&   ./configure --enable-hash &&   make &&   make install
